### ISSUE TITLE
2023 milestone

### ISSUE THREAD

**Issue by armantorkzaban** [tcfev/forDem#168]
- [ ] plug our registration method and forward app registrations via nginx rules
- [ ] choose from available open source apps
- [ ] change the app login procedure
- [ ] release with the current mas.fordem.org on app/play store
- [ ] enable Ethereum transaction
- [ ] enable ranked pairs voting
- [ ] enable Twitter authentication, (show number of followers on other platform next the Twitter name?), allow follower invitation(?)
- [ ] integrate Zemi(Map)
- [ ] enable offline mode
- [ ] integrate Zemi(Map)
- [ ] release Fordem flutter app
