### ISSUE TITLE
Todo - MVP - I

### ISSUE THREAD

**Issue by armantorkzaban** [tcfev/forDem#5]
In this MVP stage we need to include the following feature: 

## Networking
- [ ] tcfev/forDem#12
- [ ] tcfev/forDem#15

## Participation
- [ ] tcfev/fordem_app#10

## Deliberation
- [ ] tcfev/forDem#8

---
- [ ] tcfev/forDem#6
- [ ] tcfev/forDem#7
- [ ] tcfev/forDem#9
- [ ] tcfev/forDem#11
- [ ] tcfev/fordem-app#4
- [ ] tcfev/forDem#14

@zanzendegi, @lukas-h @desputinski: is this accepted by you for the MVP? If not when do we talk, if yes, when should we set the corresponding sprints?

**Comment by armantorkzaban** [comment]
This was mentioned in the protocol: 

- [ ] Establish services to guide and motivate participants for actions and prepare how-to's for initiators.

- [ ] Provide legal and organizational guides for organizers (how to register where, what rules apply)

- [ ] Services around demonstrations (sleeping places on site, carpooling in the area, mobility overview or which public connections are there - dBahn, Flixbus..)

- [ ] Information about the organizer (profile, how good were previous events), infrastructure planned on site (is there catering, public toilets,...)

@armantorkzaban @agrinpc please add to corresponding features.

**Comment by lukas-h** [comment]
> * [ ]  [Map view with civil society organizations and initiatives, as well as an editor for registering them #6](https://github.com/tcfev/forDem/issues/6)
> * [ ]  [Political Calendar #7](https://github.com/tcfev/forDem/issues/7)
> * [ ]  [(tags / categories? → Subscribe to tag) #9](https://github.com/tcfev/forDem/issues/9)
> * [ ]  [Display future and ongoing citizen participation processes #11](https://github.com/tcfev/forDem/issues/11)
> * [ ]  [News feed fordem-app#9](https://github.com/tcfev/fordem-app/issues/9)
> * [ ]  [Resource and Service sharing search engine #14](https://github.com/tcfev/forDem/issues/14)

I agree with the first three (networking, deliberation, participation), but the other things kind of bloat it already.
All of the additional features don't seem to be too big, so they could later on added easily, but right now, I would guess, they could really distract from the three basic features (net, delib, partic), that are crucial for the success.
